# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

style:
  active: false

formatting:
  active: false

complexity:
  ComplexMethod:
    active: false
  TooManyFunctions:
    active: false